services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    restart: on-failure
    env_file:
      - .env
    expose:
      - "8000"
    volumes:
      - ./logs:/var/log/api
    user: "1000:1000" # Ensure consistent user mapping
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  caddy:
    image: caddy:2.10.0-alpine
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - api

volumes:
  caddy_data:
  caddy_config:
