[project]
name = "proxy-outlook"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "selenium>=4.34.2",
    "undetected-chromedriver>=3.5.5",
    "python-dotenv>=1.0.1",
    "setuptools>=70.0.0",
]
